# Generated by Django 5.1.3 on 2024-11-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
